# Generated by Django 3.1.7 on 2021-03-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, null=True)),
                ('disc', models.CharField(max_length=90, null=True)),
                ('price', models.FloatField()),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=190, null=True)),
            ],
        ),
    ]
